name: windows 10 打包工作流

on:
  push:
    branches:
      - workflow
  workflow_dispatch:

jobs:
  mc_fishing_opencv:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: 跑起来~
        run: |
          python -m pip install -U pip
          pip install pyinstaller>=6.3
          pip install -r requirements.txt
          echo "==================="
          pyinstaller tar-win.spec
          echo "==================="
          
      - name: 保存到工件
        uses: actions/upload-artifact@v4
        with:
          name: tar-win10.pyz
          path: dist/tar.pyz.exe

  # AI 给出的，还没测试
  # release:
  #   runs-on: windows-2019
  #   needs: mc_fishing_opencv
  #   steps:
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         artifact: target/my-app.jar
  #         release: v1.0.0